import schemarouter


def test_public_framework_exports_are_intentional_and_stable() -> None:
    expected = {
        "__version__",
        "ADAPTER_ENTRY_POINT_GROUP",
        "AdapterContext",
        "AdapterLoadResult",
        "AdapterPluginInfo",
        "AdapterRegistry",
        "ApprovalCallback",
        "ApprovalDeniedError",
        "BindingDriftError",
        "ConfiguredSchemaRouter",
        "CallableDecisionBackend",
        "DecisionBackend",
        "DecisionFallback",
        "DecisionPolicy",
        "DecisionCallable",
        "DecisionOption",
        "DecisionOptionTextCallable",
        "DecisionRequest",
        "DecisionResult",
        "DecisionSelection",
        "EmbeddingCallable",
        "EmbeddingDecisionBackend",
        "DefaultMCPClientFactory",
        "EndpointSpec",
        "EvidenceRequirements",
        "ExecutionBudget",
        "ExecutionBudgetExceededError",
        "ExecutionError",
        "ExecutionPlan",
        "ExecutionPolicy",
        "FieldSpec",
        "FirstOptionDecisionBackend",
        "InMemoryRegistry",
        "KeywordAnalyzer",
        "MCPClientFactory",
        "ModelAnalysisError",
        "ModelCallable",
        "ModelQueryAnalyzer",
        "OpenAPICompatibilityIssue",
        "OpenAPICompatibilityReport",
        "ParameterSpec",
        "PlanRequest",
        "PlanValidationError",
        "PlanningError",
        "PolicyViolationError",
        "ProposalApprovalError",
        "QueryAnalyzer",
        "QueryIntent",
        "RegistrationError",
        "RegistryExecutor",
        "RetryPolicy",
        "RunConfig",
        "RunEvent",
        "RunTrace",
        "RunTraceStore",
        "SchemaDriftError",
        "SchemaPlanner",
        "SchemaProposal",
        "SchemaRouter",
        "SchemaRouterError",
        "SchemaSourceError",
        "SQLiteRegistry",
        "SQLiteRunTraceStore",
        "SchemaValidationError",
        "SourceAdapter",
        "OPTIMADESourceAdapter",
        "ToolCall",
        "ToolRegistry",
        "ToolResult",
        "ToolSpec",
        "TraceError",
        "UnsupportedSchemaSourceError",
        "schema_tool",
        "tool_from_callable",
        "analyze_openapi_compatibility",
        "choose_async",
        "choose_sync",
        "discover_adapter_plugins",
        "load_adapter_plugins",
        "record_run_events",
        "replay_run_events",
    }

    assert set(schemarouter.__all__) == expected
    for name in expected:
        assert hasattr(schemarouter, name)


def test_internal_implementation_types_are_not_top_level_exports() -> None:
    internal = {
        "DocumentationModelCallable",
        "ModelIntent",
        "ProposalEndpoint",
        "ProposalField",
        "ProposalParameter",
        "PythonCallableInvoker",
        "SchemaProposalDraft",
        "inspect_documentation_url",
    }

    assert internal.isdisjoint(schemarouter.__all__)
