from ._version import __version__
from .adapters.base import AdapterContext, AdapterLoadResult, AdapterRegistry, SourceAdapter
from .adapters.mcp import DefaultMCPClientFactory, MCPClientFactory
from .adapters.optimade import OPTIMADESourceAdapter
from .adapters.python import schema_tool, tool_from_callable
from .analyzers import ModelCallable, ModelQueryAnalyzer
from .decision_policy import DecisionFallback, DecisionPolicy
from .decisions import (
    CallableDecisionBackend,
    DecisionBackend,
    DecisionCallable,
    DecisionOption,
    DecisionRequest,
    DecisionResult,
    DecisionSelection,
    FirstOptionDecisionBackend,
    choose_async,
    choose_sync,
)
from .errors import (
    ApprovalDeniedError,
    BindingDriftError,
    ExecutionBudgetExceededError,
    ExecutionError,
    ModelAnalysisError,
    PlanningError,
    PlanValidationError,
    PolicyViolationError,
    ProposalApprovalError,
    RegistrationError,
    SchemaDriftError,
    SchemaRouterError,
    SchemaSourceError,
    SchemaValidationError,
    UnsupportedSchemaSourceError,
)
from .executor import RegistryExecutor
from .openapi_compatibility import (
    OpenAPICompatibilityIssue,
    OpenAPICompatibilityReport,
    analyze_openapi_compatibility,
)
from .models import (
    EndpointSpec,
    EvidenceRequirements,
    ExecutionPlan,
    FieldSpec,
    ParameterSpec,
    PlanRequest,
    QueryIntent,
    ToolCall,
    ToolResult,
    ToolSpec,
)
from .planner import KeywordAnalyzer, QueryAnalyzer, SchemaPlanner
from .policy import ApprovalCallback, ExecutionPolicy
from .proposals import SchemaProposal
from .registry import InMemoryRegistry, ToolRegistry
from .runs import ExecutionBudget, RetryPolicy, RunConfig, RunEvent
from .runtime import ConfiguredSchemaRouter, SchemaRouter

__all__ = [
    "__version__",
    "AdapterContext",
    "AdapterLoadResult",
    "AdapterRegistry",
    "ApprovalCallback",
    "ApprovalDeniedError",
    "BindingDriftError",
    "ConfiguredSchemaRouter",
    "CallableDecisionBackend",
    "DecisionBackend",
    "DecisionFallback",
    "DecisionPolicy",
    "DecisionCallable",
    "DecisionOption",
    "DecisionRequest",
    "DecisionResult",
    "DecisionSelection",
    "DefaultMCPClientFactory",
    "EndpointSpec",
    "EvidenceRequirements",
    "ExecutionBudget",
    "ExecutionBudgetExceededError",
    "ExecutionError",
    "ExecutionPlan",
    "ExecutionPolicy",
    "FieldSpec",
    "FirstOptionDecisionBackend",
    "InMemoryRegistry",
    "KeywordAnalyzer",
    "MCPClientFactory",
    "ModelAnalysisError",
    "ModelCallable",
    "ModelQueryAnalyzer",
    "OpenAPICompatibilityIssue",
    "OpenAPICompatibilityReport",
    "ParameterSpec",
    "PlanRequest",
    "PlanValidationError",
    "PlanningError",
    "PolicyViolationError",
    "ProposalApprovalError",
    "QueryAnalyzer",
    "QueryIntent",
    "RegistrationError",
    "RegistryExecutor",
    "RetryPolicy",
    "RunConfig",
    "RunEvent",
    "SchemaDriftError",
    "SchemaPlanner",
    "SchemaProposal",
    "SchemaRouter",
    "SchemaRouterError",
    "SchemaSourceError",
    "SchemaValidationError",
    "SourceAdapter",
    "OPTIMADESourceAdapter",
    "ToolCall",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "UnsupportedSchemaSourceError",
    "schema_tool",
    "tool_from_callable",
    "analyze_openapi_compatibility",
    "choose_async",
    "choose_sync",
]
