from ._version import __version__
from .adapters.base import AdapterContext, AdapterLoadResult, AdapterRegistry, SourceAdapter
from .adapters.mcp import DefaultMCPClientFactory, MCPClientFactory
from .adapters.optimade import OPTIMADESourceAdapter
from .adapters.plugins import (
    ADAPTER_ENTRY_POINT_GROUP,
    AdapterPluginInfo,
    discover_adapter_plugins,
    load_adapter_plugins,
)
from .adapters.python import schema_tool, tool_from_callable
from .analyzers import ModelCallable, ModelQueryAnalyzer
from .dashboard import render_dashboard, write_dashboard
from .decision_policy import DecisionFallback, DecisionPolicy
from .decisions import (
    CallableDecisionBackend,
    DecisionBackend,
    DecisionCallable,
    DecisionOption,
    DecisionOptionTextCallable,
    DecisionRequest,
    DecisionResult,
    DecisionSelection,
    EmbeddingCallable,
    EmbeddingDecisionBackend,
    FirstOptionDecisionBackend,
    choose_async,
    choose_sync,
)
from .errors import (
    ApprovalDeniedError,
    BindingDriftError,
    ExecutionBudgetExceededError,
    ExecutionError,
    ExecutionHookError,
    ModelAnalysisError,
    NonRetryableInvocationError,
    PlanningError,
    PlanValidationError,
    PolicyViolationError,
    ProposalApprovalError,
    RegistrationError,
    SchemaDriftError,
    SchemaRouterError,
    SchemaSourceError,
    SchemaValidationError,
    TraceError,
    UnsupportedSchemaSourceError,
)
from .executor import RegistryExecutor
from .hooks import AfterExecutionHook, BeforeExecutionHook, ExecutionHooks
from .inspection import (
    EndpointInspection,
    ExecutionInspection,
    PlannerInspection,
    RegistryInspection,
    RouterInspection,
    ToolInspection,
    TraceInspection,
    inspect_registry,
    inspect_router,
    inspect_run_trace,
    inspect_tool,
    inspect_tool_spec,
    inspect_trace,
    inspect_traces,
    tool_spec_document,
)
from .models import (
    EndpointSpec,
    EvidenceRequirements,
    ExecutionPlan,
    FieldSpec,
    ParameterSpec,
    PlanRequest,
    QueryIntent,
    ToolCall,
    ToolResult,
    ToolSpec,
)
from .openapi_compatibility import (
    OpenAPICompatibilityIssue,
    OpenAPICompatibilityReport,
    analyze_openapi_compatibility,
)
from .planner import KeywordAnalyzer, QueryAnalyzer, SchemaPlanner
from .policy import ApprovalCallback, ExecutionPolicy
from .proposals import SchemaProposal
from .registry import InMemoryRegistry, SQLiteRegistry, ToolRegistry
from .runs import ExecutionBudget, RetryPolicy, RunConfig, RunEvent
from .runtime import ConfiguredSchemaRouter, SchemaRouter
from .schema_diff import (
    SchemaChange,
    SchemaChangeSeverity,
    SchemaCompatibility,
    SchemaDiffReport,
    compare_endpoint_specs,
    compare_tool_specs,
)
from .traces import (
    RunTrace,
    RunTraceStore,
    SQLiteRunTraceStore,
    record_run_events,
    replay_run_events,
)

__all__ = [
    "__version__",
    "ADAPTER_ENTRY_POINT_GROUP",
    "AdapterContext",
    "AdapterLoadResult",
    "AdapterPluginInfo",
    "AdapterRegistry",
    "ApprovalCallback",
    "AfterExecutionHook",
    "ApprovalDeniedError",
    "BeforeExecutionHook",
    "BindingDriftError",
    "ConfiguredSchemaRouter",
    "CallableDecisionBackend",
    "DecisionBackend",
    "DecisionFallback",
    "DecisionPolicy",
    "DecisionCallable",
    "DecisionOption",
    "DecisionOptionTextCallable",
    "DecisionRequest",
    "DecisionResult",
    "DecisionSelection",
    "EmbeddingCallable",
    "EmbeddingDecisionBackend",
    "DefaultMCPClientFactory",
    "EndpointSpec",
    "EvidenceRequirements",
    "ExecutionBudget",
    "ExecutionBudgetExceededError",
    "ExecutionError",
    "ExecutionHookError",
    "ExecutionHooks",
    "ExecutionPlan",
    "ExecutionPolicy",
    "FieldSpec",
    "FirstOptionDecisionBackend",
    "InMemoryRegistry",
    "EndpointInspection",
    "ExecutionInspection",
    "PlannerInspection",
    "RegistryInspection",
    "RouterInspection",
    "ToolInspection",
    "TraceInspection",
    "KeywordAnalyzer",
    "MCPClientFactory",
    "ModelAnalysisError",
    "ModelCallable",
    "ModelQueryAnalyzer",
    "NonRetryableInvocationError",
    "OpenAPICompatibilityIssue",
    "OpenAPICompatibilityReport",
    "ParameterSpec",
    "PlanRequest",
    "PlanValidationError",
    "PlanningError",
    "PolicyViolationError",
    "ProposalApprovalError",
    "QueryAnalyzer",
    "QueryIntent",
    "RegistrationError",
    "RegistryExecutor",
    "RetryPolicy",
    "RunConfig",
    "RunEvent",
    "RunTrace",
    "RunTraceStore",
    "SQLiteRunTraceStore",
    "SchemaDriftError",
    "SchemaChange",
    "SchemaChangeSeverity",
    "SchemaCompatibility",
    "SchemaDiffReport",
    "SchemaPlanner",
    "SchemaProposal",
    "SchemaRouter",
    "SchemaRouterError",
    "SchemaSourceError",
    "SQLiteRegistry",
    "SchemaValidationError",
    "SourceAdapter",
    "OPTIMADESourceAdapter",
    "ToolCall",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "TraceError",
    "UnsupportedSchemaSourceError",
    "schema_tool",
    "tool_from_callable",
    "analyze_openapi_compatibility",
    "choose_async",
    "choose_sync",
    "compare_endpoint_specs",
    "compare_tool_specs",
    "discover_adapter_plugins",
    "inspect_registry",
    "inspect_router",
    "inspect_run_trace",
    "inspect_tool",
    "inspect_tool_spec",
    "inspect_trace",
    "inspect_traces",
    "load_adapter_plugins",
    "tool_spec_document",
    "record_run_events",
    "render_dashboard",
    "replay_run_events",
    "write_dashboard",
]
